export const beneficios = [

    // ==========================================
    // TIQUETERA EMOCIONAL
    // ==========================================

    // CATEGORÍA: TIEMPO PARA TU VIDA
    { id: 1,  tipo: "Tiquetera", titulo: "Día libre para celebrar tu vida", diasAntelacion: 3, requiereAdjunto: false, hint: "Regálate un día solo para ti: celebra tu vida, recarga energías y comparte con quienes hacen tus días más felices. 🎂 Si tu cumpleaños cae en fin de semana o festivo, puedes tomarlo el día hábil anterior o siguiente. Solicita con mínimo 3 días de anticipación." },
    { id: 2,  tipo: "Tiquetera", titulo: "Día libre antes del gran día (matrimonio)", diasAntelacion: 8, requiereAdjunto: true, hint: "Disfruta con tranquilidad los momentos previos a uno de los días más importantes de tu vida. 💍 Aplica exclusivamente para el día hábil anterior a la ceremonia. Solicita con 8 días de anticipación. Recuerda entregar el registro del matrimonio dentro de los 8 días siguientes." },
    { id: 3,  tipo: "Tiquetera", titulo: "Día libre para organizar tu nuevo hogar", diasAntelacion: 3, requiereAdjunto: true, hint: "Dedica tiempo a construir ese espacio donde empiezan nuevas historias y sueños. 📦 Solicita con mínimo 3 días de anticipación. Recuerda presentar evidencia de mudanza." },
    { id: 4,  tipo: "Tiquetera", titulo: "Día libre para extender tu descanso (fin de semana)", diasAntelacion: 3, requiereAdjunto: false, hint: "Regálate una pausa más larga: viaja, descansa o simplemente desconéctate para volver con energía renovada. 🏖️ Solicita con mínimo 3 días de anticipación. Una vez por semestre. 📅✨" },
    { id: 5,  tipo: "Tiquetera", titulo: "Día para Trabajo desde casa", diasAntelacion: 3, requiereAdjunto: false, hint: "Encuentra un entorno que favorezca tu concentración y bienestar, trabajando desde un espacio que también es tuyo. 🏠 Solicita con mínimo 3 días de anticipación. Una vez al mes. 💻✨" },
    { id: 6,  tipo: "Tiquetera", titulo: "Desconexión temprana", diasAntelacion: 3, requiereAdjunto: false, hint: "Empieza antes tu descanso y disfruta más tiempo para ti, tu familia o aquello que te apasiona. ⏰ Jornada continua: L-J de 7:30 a.m. a 3:30 p.m. / V de 7:30 a.m. a 2:30 p.m. Solicita con mínimo 3 días de anticipación. Una vez al mes. ✨" },
    { id: 7,  tipo: "Tiquetera", titulo: "Media jornada para asuntos personales", diasAntelacion: 1, requiereAdjunto: false, hint: "Haz espacio para tu vida personal sin preocupaciones: lo importante también está fuera de la oficina. 📝 Solicita con 1 día de anticipación. Horario: 7:30-12:30 o 1:30-5:30 (L-J) / 7:30-12:30 o 1:30-4:30 (V). Una vez por semestre. ⏰✨" },
    { id: 8,  tipo: "Tiquetera", titulo: "Media jornada cuando más lo necesitas (emergencia)", diasAntelacion: 0, requiereAdjunto: false, hint: "Porque sabemos que lo inesperado ocurre, cuentas con el tiempo para atender lo que realmente importa. 🚨 Informa inmediatamente a tu jefe. Horario: 7:30-12:30 o 1:30-5:30 (L-J) / 7:30-12:30 o 1:30-4:30 (V). Hasta 2 veces por año. ⚠️" },
    { id: 9,  tipo: "Tiquetera", titulo: "Media jornada para vivir tu pasión (evento deportivo)", diasAntelacion: 3, requiereAdjunto: true, hint: "Vive tu pasión por el deporte y disfruta esos momentos que llenan de energía tu vida. ⚽ Solicita con mínimo 3 días de anticipación. Horario: 7:30-12:30 o 1:30-5:30 (L-J) / 7:30-12:30 o 1:30-4:30 (V). Una vez por semestre. Recuerda presentar evidencia del evento. 🏃‍♂️✨" },
    { id: 10, tipo: "Tiquetera", titulo: "Media jornada para disfrutar la cultura", diasAntelacion: 3, requiereAdjunto: true, hint: "Alimenta tu espíritu: conéctate con el arte, la cultura y nuevas experiencias. 🎭 Solicita con mínimo 3 días de anticipación. Horario: 7:30-12:30 o 1:30-5:30 (L-J) / 7:30-12:30 o 1:30-4:30 (V). Una vez por semestre. Recuerda presentar evidencia del evento. ✨" },

    // CATEGORÍA: BIENESTAR Y ENERGÍA
    { id: 11, tipo: "Tiquetera", titulo: "Jornada continua post maternidad para acompañar los primeros momentos", diasAntelacion: 3, requiereAdjunto: true, hint: "Extiende esos primeros momentos únicos con tu hijo/a, fortaleciendo el vínculo que transforma la vida. 👶 Aplica para el mes siguiente a finalizar la licencia de maternidad. Horario continuo: 7:30 a.m. a 4:30 p.m. Solicita con mínimo 3 días de anticipación. Recuerda presentar el registro civil. ⏰✨" },
    { id: 12, tipo: "Tiquetera", titulo: "Días adicionales para disfrutar la paternidad", diasAntelacion: 3, requiereAdjunto: true, hint: "Comparte más tiempo con tu hijo/a y sé protagonista de esos primeros recuerdos inolvidables. 👨‍👧 Aplica para los días siguientes a la licencia de paternidad. Solicita con mínimo 3 días de anticipación. Recuerda presentar el registro civil. 🎁✨" },
    { id: 13, tipo: "Tiquetera", titulo: "Día libre por duelo de un ser amado", diasAntelacion: 0, requiereAdjunto: true, hint: "En los momentos difíciles también estamos contigo. Tómate el tiempo que necesitas para acompañar, despedir y cuidar de ti y de quienes amas. 🕊️ Aplica para honras fúnebres no cubiertas por ley. Recuerda presentar certificado de defunción o aviso exequial. 🖤" },
    { id: 14, tipo: "Tiquetera", titulo: "Media jornada para acompañar a tu familia", diasAntelacion: 3, requiereAdjunto: false, hint: "Porque estar presente también es cuidar: acompaña a los tuyos cuando más lo necesitan. 🤝 Solicita con mínimo 3 días de anticipación. Horario: 7:30-12:30 o 1:30-5:30 (L-J) / 7:30-12:30 o 1:30-4:30 (V). Hasta 2 veces por año. ⏰✨" },
    { id: 15, tipo: "Tiquetera", titulo: "Media jornada para celebrar a alguien especial", diasAntelacion: 3, requiereAdjunto: true, hint: "Celebra junto a quienes hacen tu vida más significativa en un día que merece ser compartido. 🎁 Solicita con mínimo 3 días de anticipación. Horario: 7:30-12:30 o 1:30-5:30 (L-J) / 7:30-12:30 o 1:30-4:30 (V). Hasta 2 veces por año. Recuerda tener el documento de identidad de la persona. ✨" },
    { id: 16, tipo: "Tiquetera", titulo: "Media jornada para celebrar el amor (aniversario de bodas o unión)", diasAntelacion: 3, requiereAdjunto: true, hint: "Dedica este tiempo a fortalecer el vínculo con tu pareja y celebrar juntos una historia construida con amor, compromiso y compañía. 💑 Solicita con mínimo 3 días de anticipación. Horario: 7:30-12:30 o 1:30-5:30 (L-J) / 7:30-12:30 o 1:30-4:30 (V). Una vez por año. Recuerda presentar registro civil de matrimonio o documento equivalente. ✨" },
    { id: 17, tipo: "Tiquetera", titulo: "Media jornada para el cuidado de tu mascota", diasAntelacion: 3, requiereAdjunto: false, hint: "Tu mascota también es familia: dedícale tiempo, cuidado y cariño. 🐶 Solicita con mínimo 3 días de anticipación. Horario: 7:30-12:30 o 1:30-5:30 (L-J) / 7:30-12:30 o 1:30-4:30 (V). Hasta 2 veces por año. Soporte opcional: cita o control veterinario. 🐾✨" },
    { id: 18, tipo: "Tiquetera", titulo: "Media jornada por servir y cuidar a todos (brigadista o comité de convivencia)", diasAntelacion: 3, requiereAdjunto: false, hint: "Tu compromiso hace la diferencia. Reconocemos tu labor brindándote un espacio para recargar y continuar cuidando a los demás. 🤝 Debes ser miembro activo. Solicita con mínimo 3 días de anticipación. Horario: 7:30-12:30 o 1:30-5:30 (L-J) / 7:30-12:30 o 1:30-4:30 (V). Una vez por semestre. ✨" },
    { id: 19, tipo: "Tiquetera", titulo: "Día libre por elegir movilidad sostenible", diasAntelacion: 3, requiereAdjunto: true, hint: "Tu compromiso con el planeta también cuenta. 🌿 Disfruta un día para ti como reconocimiento por aportar a una movilidad más limpia y consciente, conforme a la Ley 1811 de 2016. Solicita con mínimo 3 días de anticipación. Recuerda presentar el reporte de uso de bicicleta. 🚲✨" },

    // CATEGORÍA: CRECIMIENTO CON PROPÓSITO
    { id: 20, tipo: "Tiquetera", titulo: "Día libre por evaluación sobresaliente", diasAntelacion: 3, requiereAdjunto: false, hint: "Reconocemos tu compromiso y excelencia: tómate un día para celebrar tus logros y sentirte orgulloso/a de tu crecimiento. 🏆 Solicita con mínimo 3 días de anticipación. Una vez por semestre." },
    { id: 21, tipo: "Tiquetera", titulo: "Día libre para celebrar tu graduación", diasAntelacion: 8, requiereAdjunto: true, hint: "Celebra el fruto de tu esfuerzo y disciplina: este logro merece ser vivido plenamente. 🎓 Solicita con 8 días de anticipación. Aplica para el día de la ceremonia de graduación (pregrado y posgrado). Recuerda presentar el documento de la institución con la fecha del grado. 📎✨" },
    { id: 22, tipo: "Tiquetera", titulo: "Media jornada para potenciar tu estudio (preparación académica)", diasAntelacion: 3, requiereAdjunto: true, hint: "Regálate un espacio para concentrarte en tus metas académicas. Aprovecha este tiempo para preparar exámenes finales o avanzar en tu trabajo de grado con tranquilidad y enfoque. 🎓 Solicita con 3 días de anticipación. Aplica para estudios formales en curso. Recuerda presentar certificación de estudio. 📚✨" },

    // ==========================================
    // SITUACIONES ADMINISTRATIVAS (sin cambios)
    // ==========================================
    { id: 23, tipo: "Administrativos", titulo: "Licencia Ordinaria no remunerada", diasAntelacion: 5, requiereAdjunto: false, hint: "Un empleado se encuentra en licencia ordinaria cuando transitoriamente se separa del ejercicio de su cargo y sin remuneración. Su duración es por sesenta (60) días hábiles al año, continuos o discontinuos, los cuales podrán prorrogarse hasta por treinta (30) días hábiles más siempre que exista justa causa justificada a juicio del nominador." },
    { id: 24, tipo: "Administrativos", titulo: "Licencia no remunerada para adelantar estudios", diasAntelacion: 5, requiereAdjunto: true, hint: "Un empleado se encuentra en licencia no remunerada para adelantar estudios cuando transitoriamente se separa del ejercicio de su cargo por solicitud propia y sin remuneración, con el fin de cursar estudios de educación formal y para el trabajo y el desarrollo humano." },
    { id: 25, tipo: "Administrativos", titulo: "Licencia remunerada por enfermedad", diasAntelacion: 1, requiereAdjunto: true, hint: "Es la licencia que se autoriza cuando el empleado se encuentra en incapacidad mediante acto administrativo motivado, de oficio o a solicitud de parte, previa certificación expedida por autoridad competente." },
    { id: 26, tipo: "Administrativos", titulo: "Licencia por maternidad", diasAntelacion: 1, requiereAdjunto: true, hint: "Es una situación administrativa en virtud de la cual se brinda a la madre un receso remunerado para que se recupere del parto y le dedique al recién llegado el cuidado y la atención requerida." },
    { id: 27, tipo: "Administrativos", titulo: "Licencia por paternidad", diasAntelacion: 1, requiereAdjunto: true, hint: "Es una situación administrativa que le permite al padre compartir con su recién nacido (a), con el objetivo primordial de privilegiar los derechos del menor, es decir, que lo perseguido por el legislador es garantizar la efectividad de los derechos que son inherentes a la misma circunstancia del nacimiento." },
    { id: 28, tipo: "Administrativos", titulo: "Licencia por luto", diasAntelacion: 1, requiereAdjunto: true, hint: "Es una situación administrativa en la que se busca que el empleado público cuente con un tiempo prudencial que le permita volver a retomar sus actividades laborales, entendiendo el duelo como la pena, el sufrimiento y el desamparo emocional causado por la muerte o la pérdida de un ser querido." },
    { id: 29, tipo: "Administrativos", titulo: "Permiso Hasta por un (1) dia", diasAntelacion: 2, requiereAdjunto: false, hint: "Los jefes inmediatos de las respectivas dependencias, tendrán la competencia para autorizar o negar a los empleados públicos a su cargo, permiso ocasional remunerado durante la jornada laboral, el cual no puede superar la duración de esta." },
    { id: 30, tipo: "Administrativos", titulo: "Permiso Hasta por tres (3) dias", diasAntelacion: 3, requiereAdjunto: false, hint: "El Director General puede autorizar o negar mediante acto administrativo, con el visto bueno del jefe inmediato y según las necesidades del servicio, un permiso remunerado de hasta tres días hábiles continuos o discontinuos por justa causa." },
    { id: 31, tipo: "Administrativos", titulo: "Permiso por calamidad", diasAntelacion: 0, requiereAdjunto: false, hint: "El Director General puede autorizar o negar mediante acto administrativo permiso hasta por cinco (5) días continuos o discontinuos, por cada situación que la origina. El empleado deberá informar de la situación de forma inmediata y, una vez se reincorpore a sus funciones, justificar." },
    { id: 32, tipo: "Administrativos", titulo: "Permiso para citas medicas", diasAntelacion: 1, requiereAdjunto: false, hint: "Los permisos para citas médicas deben solicitarse con un día de antelación, salvo que sean urgentes." },
    { id: 33, tipo: "Administrativos", titulo: "Permiso academico compensado", diasAntelacion: 5, requiereAdjunto: true, hint: "El Director General puede autorizar o negar mediante acto administrativo, previo visto bueno del jefe inmediato sujeto a las necesidades del servicio, para que se otorgue al empleado permiso académico compensado de hasta dos (2) horas diarias o hasta cuarenta (40) horas mensuales, por dos (2) años, prorrogables por un (1) año, para adelantar programas académicos de educación superior en la modalidad de posgrado en instituciones legalmente reconocidas." },
    { id: 34, tipo: "Administrativos", titulo: "Permiso para ejercer la docencia universitaria", diasAntelacion: 5, requiereAdjunto: true, hint: "El Director General puede autorizar o negar, previo visto bueno del jefe inmediato sujeto a las necesidades del servicio, para que reconozca al empleado permiso para el ejercicio de la docencia universitaria, dentro de la jornada laboral ordinaria, hasta por cinco (5) horas semanales." },
    { id: 35, tipo: "Administrativos", titulo: "Permiso por Matrimonio", diasAntelacion: 5, requiereAdjunto: true, hint: "El Director General puede autorizar o negar mediante acto administrativo, previo visto bueno del jefe inmediato sujeto a las necesidades del servicio, permiso por tres (3) días hábiles, cuando contraiga matrimonio." },
    { id: 36, tipo: "Administrativos", titulo: "Permiso como incentivo", diasAntelacion: 5, requiereAdjunto: false, hint: "El jefe inmediato puede autorizar o negar, sujeto a las necesidades del servicio, permiso como incentivo, el cual corresponde a un (1) día de descanso remunerado, cuando se alcanza el nivel sobresaliente en la escala de evaluación del desempeño por cada semestre evaluado, para los empleados de carrera administrativa y los de libre nombramiento y remoción pertenecientes a los niveles profesional y asistencial." },
    { id: 37, tipo: "Administrativos", titulo: "Permiso para la lactancia", diasAntelacion: 5, requiereAdjunto: true, hint: "La mujer en lactancia, una vez reincorporada a sus labores normales, tiene derecho a que se le conceda un permiso especial durante el día para poder amamantar su hijo: dos descansos de treinta (30) minutos cada uno o de una (1) hora diaria, durante los primeros (6) meses de edad." },
    { id: 38, tipo: "Administrativos", titulo: "Permiso por ejercicio del cargo de jurado de votacion", diasAntelacion: 5, requiereAdjunto: true, hint: "El jefe inmediato puede autorizar o negar, sujeto a las necesidades del servicio, al empleado que hubiese sido designado jurado de votación, el derecho a un (1) día compensatorio de descanso remunerado dentro de los cuarenta y cinco (45) días hábiles siguientes a la votación." },
    { id: 39, tipo: "Administrativos", titulo: "Permiso por ejercer el derecho al voto", diasAntelacion: 5, requiereAdjunto: true, hint: "El jefe inmediato puede autorizar o negar, sujeto a las necesidades del servicio, al empleado que hubiese hecho uso del voto o sufragio, el derecho a hacer efectivo el descanso remunerado consistente en media jornada, el cual deberá disfrutarse dentro del mes siguiente a la votación." },
    { id: 40, tipo: "Administrativos", titulo: "Permiso por uso de bicicletas", diasAntelacion: 5, requiereAdjunto: true, hint: "De conformidad con la Ley 1811 de 2016 se concederá como incentivo a los empleados públicos, el disfrute de medio día laboral remunerado por cada treinta (30) veces que certifique haber llegado a laborar en bicicleta." }
];
